# github-actions-xcode-test
name: CI

# CIを回すタイミングは「branches:」にpushされた時 ＆ pull_request作成時。
#「paths-ignore:」の変更時はCIを回さない。
#「workflow_dispatch:」はGitHubのUIから手動でワークフローを起動するため。
on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
  pull_request:
    paths-ignore:
      - Docs/**
      - README.md
      - LICENSE
  workflow_dispatch:

# 環境変数の設定(何か触るならここを触って)
env:
 OS: macos-13
 DEVELOPER_DIR: /Applications/Xcode_15.0.app
 PLATFORM: iOS Simulator
 PLATFORM_NAME: iPhone 15 Pro Max
 PROJECT_NAME: github-actions-xcode-test
 PROJECT_WORKSPACE: github-actions-xcode-test.xcworkspace
 PROJECT_SCHEME: github-actions-xcode-test
 SKIP_TESTING_NAME: github-actions-xcode-testUITests

jobs:
  test:
    name: build for ${{ matrix.environment }}
    runs-on: env.OS
    strategy:
      # 一つのジョブが失敗しても、他のジョブがキャンセルされないように
      fail-fast: false
      matrix:
        environment: ["main"]

    steps:
    # チェックアウト
    - uses: actions/checkout@v3

    # Xcodeの一覧出力
    - name: Show Xcode list
      run: ls /Applications | grep 'Xcode'

    # Xcodeのバージョン出力
    - name: Show Xcode version
      run: xcodebuild -version

    # CocoaPodsをインストールする
    - name: CocoaPods
      run: pod install

    # ビルド
    - name: Xcode build
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -workspace env.PROJECT_WORKSPACE
        -scheme env.PROJECT_SCHEME
        build

    # 単体テストの実行
    - name: Xcode test
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -workspace env.PROJECT_WORKSPACE
        -scheme env.PROJECT_SCHEME
        -destination 'platform=${{ env.PLATFORM }},name=${{ env.PLATFORM_NAME }}'
        -skip-testing:env.SKIP_TESTING_NAME
        clean test

    # テスト結果のアップロード
    - name: Upload test results Artifact
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-results
        path: |
          Reports/*.xcresult
        if-no-files-found: error
        retention-days: 14

    # 単体テストログのアップロード
    - name: Upload test log Artifact
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: xcodebuild-logs
        path: |
          Reports/*_Test.log
        if-no-files-found: ignore
        retention-days: 14

  show-test-results:
    runs-on: env.OS
    permissions:
      checks: write
    needs: test

    steps:
    # チェックアウト
    - uses: actions/checkout@v3

    # テスト結果のダウンロード
    - name: Download test results artifact
      uses: actions/download-artifact@v3
      with:
        name: test-results
        path: Reports

    # テスト結果のマージ
    - name: Merge test results
      run: make merge-test-results

    # テスト結果の表示とアップロード
    - uses: kishikawakatsumi/xcresulttool@v1
      if: success() || failure()
      with:
        path: Reports/TestResults.xcresult
