name: CI

on: [push]

# 動作バージョンの指定
env:
 DEVELOPER_DIR: /Applications/Xcode_15.0.app

jobs:
  build:
    name: build for ${{ matrix.environment }}
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        environment: ["main"]

    steps:
    # チェックアウト
    - uses: actions/checkout@v3

    # CocoaPodsをインストールする
    - name: CocoaPods
      run: pod install
      
    # セットアップ
#    - name: Install Command Line Tools for Xcode
#    run: sudo xcode-select -s /Library/Developer/CommandLineTools
#    shell: bash

    # ビルド
    - name: Xcode build for ${{ matrix.environment }}
      run: |
        make build-debug-${{ matrix.environment }}

    # ビルドログのアップロード
    - name: Upload build log Artifact
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: xcodebuild-logs
        path: |
          Reports/*_Build.log
        if-no-files-found: ignore
        retention-days: 14

  test:
    name: test for ${{ matrix.name }}
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        name: ["develop", "production", "app-module"]

    steps:
    # チェックアウト
    - uses: actions/checkout@v3

    # セットアップ
    - uses: ./.github/workflows/templates/setup-ios

    # モックの生成
    - name: Generate mocks with Mockolo
      run: make generate-mocks

    # 単体テストの実行
    - name: Xcode test
      run: |
        make test-debug-${{ matrix.name }}

    # テスト結果のアップロード
    - name: Upload test results Artifact
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-results
        path: |
          Reports/*.xcresult
        if-no-files-found: error
        retention-days: 14

    # 単体テストログのアップロード
    - name: Upload test log Artifact
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: xcodebuild-logs
        path: |
          Reports/*_Test.log
        if-no-files-found: ignore
        retention-days: 14

  show-test-results:
    runs-on: macos-13
    permissions:
      checks: write
    needs: test

    steps:
    # チェックアウト
    - uses: actions/checkout@v3

    # テスト結果のダウンロード
    - name: Download test results artifact
      uses: actions/download-artifact@v3
      with:
        name: test-results
        path: Reports

    # テスト結果のマージ
    - name: Merge test results
      run: make merge-test-results

    # テスト結果の表示とアップロード
    - uses: kishikawakatsumi/xcresulttool@v1
      if: success() || failure()
      with:
        path: Reports/TestResults.xcresult

  info:
    runs-on: macos-13

    steps:
    # チェックアウト
    - uses: actions/checkout@v3

    # 情報の出力
    - uses: ./.github/workflows/templates/output-info
