name: CI

on: [push]

# 動作バージョンの指定
env:
 DEVELOPER_DIR: /Applications/Xcode_15.0.app

jobs:
  build:
    name: build for ${{ matrix.environment }}
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        environment: ["main"]

    steps:
    # チェックアウト
    - uses: actions/checkout@v3

    # Xcodeの一覧出力
    - name: Show Xcode list
      run: ls /Applications | grep 'Xcode'

    # Xcodeのバージョン出力
    - name: Show Xcode version
      run: xcodebuild -version

    # CocoaPodsをインストールする
    - name: CocoaPods
      run: pod install

    # ビルド
    - name: Xcode build
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -workspace github-actions-xcode-test.xcworkspace
        -scheme github-actions-xcode-test
        build

    # 単体テストの実行
    - name: Xcode test
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -workspace github-actions-xcode-test.xcworkspace
        -scheme github-actions-xcode-test
        -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max'
        -skip-testing:github-actions-xcode-testUITests
        clean test

  info:
    runs-on: macos-13

    steps:
    # Xcodeの一覧出力
    - name: Show Xcode list
      run: ls /Applications | grep 'Xcode'

    # Xcodeのバージョン出力
    - name: Show Xcode version
      run: xcodebuild -version
