name: iOS CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode-version: ['15.0']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Xcode
      uses: actions/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode-version }}
    - name: Install dependencies
      run: |
        gem install cocoapods
        pod install
    - name: Run Unit Tests
      run: xcodebuild test -workspace YourWorkspace.xcworkspace -scheme YourScheme -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.0'
